# Generated by Django 4.0.1 on 2022-03-22 21:07

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiameterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('file_name', models.CharField(max_length=250)),
                ('file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('diameter', models.FloatField(default=0)),
                ('participant_index', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_model', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_time', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'diameter_info',
            },
        ),
    ]
